name: qt-build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        run: |
          sudo apt-get update >/dev/null && sudo apt-get install -y --no-install-recommends qt5-qmake qt5-qmake-bin qtbase5-dev qtbase5-private-dev qtbase5-dev-tools libqt5sql5-mysql >/dev/null

      - name: Install QtMqtt
        run: |
          git clone https://code.qt.io/qt/qtmqtt.git
          cd qtmqtt/
          git checkout 5.15.2
          qmake
          make
          sudo make install

      - name: Run qmake
        run: |
          cd eco-classroom-desktop && qmake

      - name: Run make
        run: |
          cd eco-classroom-desktop && make
